services:
    nl_user.reset.listener:
        class: NL\UserBundle\Listener\ResetPasswordListener
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_listener, event: users.reset_all_passwords, method: onResetPassword, monolog.logger: 'users' }
